stages:
  - test
  - deploy

image: docker:latest

services:
- docker:dind

before_script:
- docker info

test_job:
  stage: test
  script:
    - ci/mailtrain_test

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/mailtrain_deploy
