version : '2'

services:
  mailtrain:
    image: nextindex/alpine-mailtrain:1.24.0
    networks:
      - front
      - back
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - mailtrain-node-config:/app/config
      - mailtrain-node-data:/app/public/grapejs/uploads
      - mailtrain-node-data:/app/public/mosaico/uploads
      - mailtrain-node-reports:/app/protected/reports
  db:
    image: mariadb:10.3.1
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
    volumes:
      - mailtrain-mysq-data:/var/lib/mysql
    networks:
      - back
  redis:
    image: redis:4.0.1
    volumes:
      - mailtrain-redis-data:/data
networks:
  front:
  back:

volumes:
  mailtrain-mysq-data: {}
  mailtrain-redis-data: {}
  mailtrain-node-data: {}
  mailtrain-node-config: {}
  mailtrain-node-reports: {}

