#!/bin/sh

set -e

docker build -t nextindex/alpine-mailtrain:latest .
docker inspect nextindex/alpine-mailtrain:latest

docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
docker push nextindex/alpine-mailtrain:latest
